
# Notes for 18860924001.xml

[n1]
lemma = 
note = Peter Nansens lillebror Immanuel Nansen (1867-1934), cand.jur. 1890, derefter ansat ved De Danske Statsbaner, 1895 fuldm√¶gtig, fra 1927 afdelingschef; gift 1892 med Christiane Nansen