
# Notes for 19060415001.xml

[n1]
lemma = 
note = Rollen som Rebekka West i den norske dramatikerHenrik Ibsens skuespilRosmersholm      

[n2]
lemma = 
note = Skuespilleren Johannes Nielsen (1870-1935), som ved ops√¶tningen i 1906 spillede hovedrollen som Johannes Rosmer      

[n3]
lemma = 
note = Knud Ernst, som har bragt dette brev til Betty Nansen og ventet svar med tilbage