
# Notes for 18850617001.xml

[n1]
lemma = 
note = Emnet for Bangs afsluttende forel√¶sning i Bergen, tirsdag 16.6.1885, var nordmandenAlexander Kiellands (1849-1906) forfatterskab      

[n2]
lemma = 
note = Har ikke kunnet identificeres; antagelig en avis i Bergen