
# Notes for 19070524001.xml

[n1]
lemma = "er nu i Orden"
note = '''Se også Bangs brev til Peter Nansen, dateret 27.5.1907'''
      

[n2]
lemma = "da Nansen ikke er kommen hjem endnu"
note = '''Peter Nansen (1861-1918), litterær direktør hos Gyldendal, befandt sig i Stockholm sammen med sin kone Betty Nansen, jf. Bangs telegram til Betty Nansen, dateret 23.5.1907'''
