
# Notes for 19080719001.xml

[n1]
lemma = " "
note = '''Bangs artikel "Jonas Lie. Hans Billede" i Tilskueren, august 1908, s. 666-681'''
      

[n2]
lemma = " "
note = '''Betty Nansen'''
      

[n3]
lemma = " "
note = '''Gustav Philipsen, redaktør (s.m. kunsthistorikeren Mario Krohn ) af Tilskueren'''
