
# Notes for 18870121001.xml

[n1]
lemma = "under Valgets frygteligste Tummel"
note = '''Valgkampen op til det danske landstings- og folketingsvalg fredag 28.1.1887, jf. brevet 8.1.1887'''
      

[n2]
lemma = "din Potte-Gang"
note = '''Peter Nansen aftjente i 1887 sin værnepligt som sygepasser ved et militærhospital, jf. brevet 8.1.1887'''
