
# Notes for 19011101003.xml

[n1]
lemma = "Forlaget"
note = '''Dvs. Det Schubotheske Forlag, KÃ¸benhavn'''
      

[n2]
lemma = "3die Korrektur"
note = '''Bang sigter til det afsluttende korrekturtryk til sin bog _Det graa Hus_, der udkom 26.11.1901'''
      
      

[n4]
lemma = "efter vedlagte Adresse"
note = '''Nogen vedlagt adresse er ikke bevaret sammen med brevet'''
