
# Notes for 19090712001.xml

[n1]
lemma = "Jeg sender alligevel dette i Stumper"
note = '''Uvist manuskript, som Bang sender en del af til Peter Nansen/Gyldendal; m√•ske_Helg_, jf. note til brevet 19080826'''
